### ISSUE TITLE
GA Post Fails if Wowza Application Name has space....

### ISSUE THREAD

**Issue by 2P2-Anthony** [WowzaMediaSystems/wse-plugin-analytics#1]
If you have a space in the Wowza Application Name, the call to Google Analytics fails. The AppName variable needs to have the space character replaced with %20.  A full fix should be URI encoding the appName, and GAPrefix variables:

	public GoogleAnalytics(String appname, String urchin, String domain, String host, String prefix)
	{
		appName = appname;
		urchinCode = urchin;
		gaDomain = domain;
		gaHost = host;
		GAPrefix = prefix;
	}

Additionally, since GAPrefix is optional, the pre-pend of GAPrefix should be dependent upon it containing data. If GAPrefix is null, then it should not be added to the QueryString string.

		String eventCaller = "http://www.google-analytics.com/__utm.gif?utmdt=" + stream + "&utmt=event&utme=5(" + eventName + "*" + eventType + "*" + stream + ")&utmwv=4.4sh" + "&utmn=" + generateUTMN() + "&utmhn=" + gaDomain + "&utmr=" + referrer + "&utmp=%2F" + GAPrefix + "%2F" + appName + "%2F" + stream + "&utmac=" + urchinCode + "&utmcc=" + utmcc + "&utmvid=" + visitorID + "&utmip=" + returnGAIP(ipaddress) + "&uip=" + returnGAIP(ipaddress);

Lastly, I believe you have the Action and Categories reversed. Currently, when data is posted for events, the actions says "HTTPCupertino" or "rtmp", whereas the category says "play" or "stop".

**Comment by rogerlittin** [comment]
Hi,

I've modified the request so that the variables are now URLEncoded which should stop the requests from breaking. We will need to have a closer look at the other two issues.

Thanks,

Roger.
